### ISSUE TITLE
Blin thinks there's a missing dependency

### ISSUE THREAD

**Issue by lizmat** [vrurg/raku-WWW-GCloud-API-Storage#1]
See https://github.com/rakudo/rakudo/issues/5429   Also  WWW::GCloud::API::Vision and WWW::GCloud

**Comment by vrurg** [comment]
Funny that you report it to the only module of three where this dependency exists. :) 

Anyway, I think the error for this module was inducted by `WWW::GCloud` where in the latest release it is missing. Though the problem has been fixed independently in https://github.com/vrurg/raku-WWW-GCloud/commit/f03f5f30e87f0807593cd8f73c7f4829cf1490ef. I'm just unsure if it worth releasing a new version with this being the only change.

Closing it here and will continue in rakudo/rakudo#5429

**Comment by vrurg** [comment]
Thank you!
